Name: Harshvardhan Tyagi
Student Id: 8856516

In [59]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns


* Load the dataset

In [61]:
df = pd.read_csv('Lab2_dataset.csv')
df.head(5)

Unnamed: 0 label                                               text   
0         605   ham  Subject: enron methanol ; meter # : 988291\nth...  \
1        2349   ham  Subject: hpl nom for january 9 , 2001\n( see a...   
2        3624   ham  Subject: neon retreat\nho ho ho , we ' re arou...   
3        4685  spam  Subject: photoshop , windows , office . cheap ...   
4        2030   ham  Subject: re : indian springs\nthis deal is to ...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

Use the CountVectorizer function in sklearn to transform the "text" feature to a vector representation of a predetermined size.

In [62]:

from sklearn.feature_extraction.text import CountVectorizer

# Assuming 'text' is the name of the column containing text data
text_data = df['text'].tolist()

# Create a CountVectorizer instance
vectorizer = CountVectorizer()

# Fit and transform the text data
X = vectorizer.fit_transform(text_data)

# Now, X contains the vectorized representation of the "text" feature
X_array = X.toarray()
feature_names = vectorizer.get_feature_names_out()

# Print the matrix
print(X_array)

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Split the dataset into training and testing

In [63]:

X = df['text'] 
y = df['label']  

# Split the dataset into training and testing sets 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



Model Training and Evaluation 

Train the Sklearn SVC model on the training dataset and evaluate on the test set

In [64]:

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.feature_extraction.text import CountVectorizer

# Assuming you have a DataFrame 'df' with 'label' and 'text' columns

# Step 1: Preprocess the text data (e.g., lowercase and tokenization)
df['text'] = df['text'].str.lower()
# Additional preprocessing steps can be added here.

# Step 2: Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['label'], test_size=0.2, random_state=42)

# Step 3: Create a CountVectorizer instance and fit/transform the text data
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# Step 4: Train the SVC model
svc_model = SVC(kernel='linear', random_state=42)
svc_model.fit(X_train_vec, y_train)

# Step 5: Evaluate the model
accuracy = svc_model.score(X_test_vec, y_test)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.97


Train and evaluate also on the Gaussian and Multinomial Naiive Bayes Classifiers

In [65]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# Load your dataset using Pandas
# Assuming you have a DataFrame 'df' with columns 'label' and 'text'

# Split the dataset into training and testing sets
X = df['text']
y = df['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Vectorize the text data using CountVectorizer
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# Train Gaussian Naive Bayes classifier
gnb = GaussianNB()
gnb.fit(X_train_vec.toarray(), y_train)
gnb_pred = gnb.predict(X_test_vec.toarray())

# Train Multinomial Naive Bayes classifier
mnb = MultinomialNB()
mnb.fit(X_train_vec, y_train)
mnb_pred = mnb.predict(X_test_vec)

# Evaluate Gaussian Naive Bayes
gnb_accuracy = accuracy_score(y_test, gnb_pred)
gnb_report = classification_report(y_test, gnb_pred)

# Evaluate Multinomial Naive Bayes
mnb_accuracy = accuracy_score(y_test, mnb_pred)
mnb_report = classification_report(y_test, mnb_pred)

print("Gaussian Naive Bayes Accuracy:", gnb_accuracy)
print("Gaussian Naive Bayes Classification Report:")
print(gnb_report)

print("Multinomial Naive Bayes Accuracy:", mnb_accuracy)
print("Multinomial Naive Bayes Classification Report:")
print(mnb_report)


Gaussian Naive Bayes Accuracy: 0.9545893719806763
Gaussian Naive Bayes Classification Report:
              precision    recall  f1-score   support

         ham       0.95      0.99      0.97       742
        spam       0.96      0.87      0.92       293

    accuracy                           0.95      1035
   macro avg       0.96      0.93      0.94      1035
weighted avg       0.95      0.95      0.95      1035

Multinomial Naive Bayes Accuracy: 0.9719806763285024
Multinomial Naive Bayes Classification Report:
              precision    recall  f1-score   support

         ham       0.98      0.98      0.98       742
        spam       0.96      0.95      0.95       293

    accuracy                           0.97      1035
   macro avg       0.97      0.96      0.97      1035
weighted avg       0.97      0.97      0.97      1035



Compare between the performance of all models and comment on the reasons behind the differences seen between the three models.

* All three models, Gaussian Naive Bayes, Multinomial Naive Bayes, and Support Vector Classifier (SVC), achieve high accuracy in classifying 'ham' and 'spam' messages. Multinomial Naive Bayes performs the best overall, with the highest precision, recall, and F1-score. The choice of the best model depends on your specific needs and trade-offs between precision and recall.

## PART B

Use the AB_NYC_2019.csv dataset for this part.

In [66]:
df = pd.read_csv('AB_NYC_2019.csv')
df.head(5)

id                                              name  host_id   
0  2539                Clean & quiet apt home by the park     2787  \
1  2595                             Skylit Midtown Castle     2845   
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632   
3  3831                   Cozy Entire Floor of Brownstone     4869   
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192   

     host_name neighbourhood_group neighbourhood  latitude  longitude   
0         John            Brooklyn    Kensington  40.64749  -73.97237  \
1     Jennifer           Manhattan       Midtown  40.75362  -73.98377   
2    Elisabeth           Manhattan        Harlem  40.80902  -73.94190   
3  LisaRoxanne            Brooklyn  Clinton Hill  40.68514  -73.95976   
4        Laura           Manhattan   East Harlem  40.79851  -73.94399   

         room_type  price  minimum_nights  number_of_reviews last_review   
0     Private room    149               1                  9  2018-10-19  \
1  Entire home/apt    225               1                 45  2019-05-21   
2     Private room    150               3                  0         NaN   
3  Entire home/apt     89               1                270  2019-07-05   
4  Entire home/apt     80              10                  9  2018-11-19   

   reviews_per_month  calculated_host_listings_count  availability_365  
0               0.21                               6               365  
1               0.38                               2               355  
2                NaN                               1               365  
3               4.64                               1               194  
4               0.10                               1                 0

Remove outliers based on price per night for a given apartment/home.

In [67]:
import pandas as pd

df = pd.read_csv('AB_NYC_2019.csv')

# Calculate Q1 and Q3
Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)

# Calculate IQR
IQR = Q3 - Q1

# Define lower and upper bounds for outlier detection
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print('lower_bound = ',lower_bound)
print('upper_bound = ',upper_bound)
# Find the outliers
outliers = df[(df["price"] < lower_bound) | (df["price"] > upper_bound)]

# Now, 'outliers' contains the rows that are outliers based on price per night
outliers

lower_bound =  -90.0
upper_bound =  334.0


id                                               name    host_id   
61        15396                 Sunny & Spacious Chelsea Apartment      60278  \
85        19601                perfect for a family or small group      74303   
103       23686  2000 SF 3br 2bath West Village private  townhouse      93790   
114       26933  2 BR / 2 Bath Duplex Apt with patio! East Village      72062   
121       27659                   3 Story Town House in Park Slope     119588   
...         ...                                                ...        ...   
48758  36420289    Rustic Garden House Apt, 2 stops from Manhattan   73211393   
48833  36450896   Brand New 3-Bed Apt in the Best Location of FiDi   29741813   
48839  36452721  Massage Spa. Stay overnight. Authors Artist dr...  274079964   
48842  36453160  LUXURY MANHATTAN PENTHOUSE+HUDSON RIVER+EMPIRE...  224171371   
48856  36457700  Large 3 bed, 2 bath , garden , bbq , all you need   66993395   

                     host_name neighbourhood_group       neighbourhood   
61                       Petra           Manhattan             Chelsea  \
85                      Maggie            Brooklyn    Brooklyn Heights   
103                        Ann           Manhattan        West Village   
114                      Bruce           Manhattan        East Village   
121                       Vero            Brooklyn         South Slope   
...                        ...                 ...                 ...   
48758                LaGabrell              Queens    Long Island City   
48833                      Yue           Manhattan  Financial District   
48839                  Richard            Brooklyn      Sheepshead Bay   
48842  LuxuryApartmentsByAmber           Manhattan             Chelsea   
48856                   Thomas            Brooklyn  Bedford-Stuyvesant   

       latitude  longitude        room_type  price  minimum_nights   
61     40.74623  -73.99530  Entire home/apt    375             180  \
85     40.69723  -73.99268  Entire home/apt    800               1   
103    40.73096  -74.00319  Entire home/apt    500               4   
114    40.72540  -73.98157  Entire home/apt    350               2   
121    40.66499  -73.97925  Entire home/apt    400               2   
...         ...        ...              ...    ...             ...   
48758  40.75508  -73.93258  Entire home/apt    350               2   
48833  40.70605  -74.01042  Entire home/apt    475               2   
48839  40.59866  -73.95661     Private room    800               1   
48842  40.75204  -74.00292  Entire home/apt    350               1   
48856  40.68886  -73.92879  Entire home/apt    345               4   

       number_of_reviews last_review  reviews_per_month   
61                     5  2018-11-03               0.12  \
85                    25  2016-08-04               0.24   
103                   46  2019-05-18               0.55   
114                    7  2017-08-09               0.06   
121                   16  2018-12-30               0.24   
...                  ...         ...                ...   
48758                  0         NaN                NaN   
48833                  0         NaN                NaN   
48839                  0         NaN                NaN   
48842                  0         NaN                NaN   
48856                  0         NaN                NaN   

       calculated_host_listings_count  availability_365  
61                                  1               180  
85                                  1                 7  
103                                 2               243  
114                                 4               298  
121                                 2               216  
...                               ...               ...  
48758                               1               364  
48833                               1                64  
48839                               1                23  
48842                

In [68]:
import pandas as pd

# Load your dataset into a Pandas DataFrame
# Assuming your dataset is in a CSV file named "your_dataset.csv"

df = pd.read_csv('AB_NYC_2019.csv')
#df.head(5)
# Calculate Q1 and Q3
Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)

# Calculate IQR
IQR = Q3 - Q1

# Define lower and upper bounds for outlier detection
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Filter the dataset to remove outliers
filtered_df = df[(df["price"] >= lower_bound) & (df["price"] <= upper_bound)]

# Now, 'filtered_df' contains the dataset with outliers removed based on price per night
filtered_df

id                                               name   host_id   
0          2539                 Clean & quiet apt home by the park      2787  \
1          2595                              Skylit Midtown Castle      2845   
2          3647                THE VILLAGE OF HARLEM....NEW YORK !      4632   
3          3831                    Cozy Entire Floor of Brownstone      4869   
4          5022   Entire Apt: Spacious Studio/Loft by central park      7192   
...         ...                                                ...       ...   
48890  36484665    Charming one bedroom - newly renovated rowhouse   8232441   
48891  36485057      Affordable room in Bushwick/East Williamsburg   6570630   
48892  36485431            Sunny Studio at Historical Neighborhood  23492952   
48893  36485609               43rd St. Time Square-cozy single bed  30985759   
48894  36487245  Trendy duplex in the very heart of Hell's Kitchen  68119814   

           host_name neighbourhood_group       neighbourhood  latitude   
0               John            Brooklyn          Kensington  40.64749  \
1           Jennifer           Manhattan             Midtown  40.75362   
2          Elisabeth           Manhattan              Harlem  40.80902   
3        LisaRoxanne            Brooklyn        Clinton Hill  40.68514   
4              Laura           Manhattan         East Harlem  40.79851   
...              ...                 ...                 ...       ...   
48890        Sabrina            Brooklyn  Bedford-Stuyvesant  40.67853   
48891        Marisol            Brooklyn            Bushwick  40.70184   
48892  Ilgar & Aysel           Manhattan              Harlem  40.81475   
48893            Taz           Manhattan      Hell's Kitchen  40.75751   
48894     Christophe           Manhattan      Hell's Kitchen  40.76404   

       longitude        room_type  price  minimum_nights  number_of_reviews   
0      -73.97237     Private room    149               1                  9  \
1      -73.98377  Entire home/apt    225               1                 45   
2      -73.94190     Private room    150               3                  0   
3      -73.95976  Entire home/apt     89               1                270   
4      -73.94399  Entire home/apt     80              10                  9   
...          ...              ...    ...             ...                ...   
48890  -73.94995     Private room     70               2                  0   
48891  -73.93317     Private room     40               4                  0   
48892  -73.94867  Entire home/apt    115              10                  0   
48893  -73.99112      Shared room     55               1                  0   
48894  -73.98933     Private room     90               7                  0   

      last_review  reviews_per_month  calculated_host_listings_count   
0      2018-10-19               0.21                               6  \
1      2019-05-21               0.38                               2   
2             NaN                NaN                               1   
3      2019-07-05               4.64                               1   
4      2018-11-19               0.10                               1   
...           ...                ...                             ...   
48890         NaN                NaN                               2   
48891         NaN                NaN                               2   
48892         NaN                NaN                               1   
48893         NaN                NaN                               6   
48894         NaN                NaN                               1   

       availability_365  
0                   365  
1                   355  
2                   365  
3                   194  
4                     0  
...                 ...  
48890                 9  
48891                36  
48892                27  
48893                 2  
48894                23  

[45923 rows x 16 columns]

Compare the Z-score approach and the whiskers approach in terms of who is better to remove the outliers in this case.

In [70]:
import pandas as pd
import numpy as np

# Define a function to remove outliers using Z-score and count outliers
def remove_outliers_zscore(dataframe, column, z_threshold=3):
    z_scores = np.abs((dataframe[column] - dataframe[column].mean()) / dataframe[column].std())
    num_outliers = (z_scores >= z_threshold).sum()  # Count outliers
    filtered_df = dataframe[z_scores < z_threshold]
    return filtered_df, num_outliers

# Define a function to remove outliers using whiskers (IQR method) and count outliers
def remove_outliers_iqr(dataframe, column):
    Q1 = dataframe[column].quantile(0.25)
    Q3 = dataframe[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    num_outliers = ((dataframe[column] < lower_bound) | (dataframe[column] > upper_bound)).sum()  # Count outliers
    filtered_df = dataframe[(dataframe[column] >= lower_bound) & (dataframe[column] <= upper_bound)]
    return filtered_df, num_outliers

# Sample DataFrame (replace this with your actual data)
data = pd.read_csv('AB_NYC_2019.csv')
df = pd.DataFrame(data)

# Remove outliers using the Z-score approach and count outliers
zscore_filtered_df, num_zscore_outliers = remove_outliers_zscore(df, "price")

# Remove outliers using the whiskers approach (IQR method) and count outliers
iqr_filtered_df, num_iqr_outliers = remove_outliers_iqr(df, "price")

print("Number of Z-score outliers:", num_zscore_outliers)
print("Number of whiskers (IQR method) outliers:", num_iqr_outliers)

# Now, zscore_filtered_df and iqr_filtered_df contain the dataset with outliers removed using their respective methods


Number of Z-score outliers: 388
Number of whiskers (IQR method) outliers: 2972


As we can see IQR Method is more appropreate in this case, as IQR method can find more number of outliers in the dataset so, we can conclude that whisker approach is suitable fot this